### ISSUE TITLE
Use Netlink to get the runtime information instead of sysfs

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#899] opened 2020-03-05 19:38 UTC
It would be very nice to use Netlink in order to retrieve the runtime information instead of reading from sysfs files. I am going to investigate this in my free time :-)

**Comment by IsmayilMirzali** [comment] 2020-04-03 21:07
Can I potentially try this in case you're busy with some other issues?

**Comment by ffmancera** [comment] 2020-04-04 20:53
Sorry but this is quite complex issue. We are currently working on this.

**Comment by tyll** [comment] 2020-07-01 09:59
Is this a duplicate of #1136?

**Comment by tyll** [comment] 2020-07-10 08:59
Closing as duplicate of #1136.

**Closed by tyll** 2020-07-10 08:59 UTC
Labels: Low priority
