### ISSUE TITLE
[nmstate-0.2.10] failed to execute nmstatectl show

### ISSUE THREAD

**Issue by rhrazdil** [nmstate/nmstate#1441] opened 2020-12-07 16:32 UTC
## Describe the bug
Running `nmstate show` sometimes fails do display current state, and fails with nmstate internal error:
libnmstate.error.NmstateInternalError: _NmClient.delete_client() should be explicitly called before python GC clean up the `object.`

## Nmstate version
0.2.10

## NetworkManager version
NetworkManager-1.22.8-5.el8_2.x86_64

## Platform
CentOS Linux release 8.1.1911 (Core) 

## How reproducible
random

## Steps to Reproduce

1. Create a bond interface with 2 slaves
```
interfaces:
- name: bond0
  type: bond
  state: up
  ipv4:
    dhcp: true
    enabled: true
  link-aggregation:
    mode: active-backup
    options:
      miimon: '140'
      primary: eth0
    slaves:
    - eth0
    - eth1
```

2. run `nmstatectl show`

## Nmstate output
- Expected output:
  Current state
- Current output:
  Failed to output current state

### Additional context
Issue was reproduced with an [e2e test in kubernetes-nmstate project](https://github.com/nmstate/kubernetes-nmstate/blob/master/test/e2e/handler/bonding_default_interface_test.go)

Full traceback:

```
Traceback (most recent call last):
  File \"/usr/lib/python3.6/site-packages/libnmstate/nm/nmclient.py\", line 275, in __del__
    \"_NmClient.delete_client() should be explicitly called \"
libnmstate.error.NmstateInternalError: _NmClient.delete_client() should be explicitly called before python GC clean up the object.
Traceback (most recent call last):
  File \"/usr/bin/nmstatectl\", line 11, in <module>
    load_entry_point('nmstate==0.2.10', 'console_scripts', 'nmstatectl')()
  File \"/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py\", line 59, in main
    return args.func(args)
  File \"/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py\", line 203, in show
    state = _filter_state(libnmstate.show(), args.only)
  File \"/usr/lib/python3.6/site-packages/libnmstate/deprecation.py\", line 40, in wrapper
    return func(*args, **kwargs)
  File \"/usr/lib/python3.6/site-packages/libnmstate/nm/nmclient.py\", line 96, in wrapped
    ret = func(*args, **kwargs)
  File \"/usr/lib/python3.6/site-packages/libnmstate/netinfo.py\", line 46, in show
    report = {Constants.INTERFACES: _interfaces()}
  File \"/usr/lib/python3.6/site-packages/libnmstate/netinfo.py\", line 115, in _interfaces
    iface_info.update(_ifaceinfo_bond(bondinfo))
  File \"/usr/lib/python3.6/site-packages/libnmstate/netinfo.py\", line 132, in _ifaceinfo_bond
    bondinfo = nm.translator.Nm2Api.get_bond_info(devinfo)
  File \"/usr/lib/python3.6/site-packages/libnmstate/nm/translator.py\", line 101, in get_bond_info
    bond_mode = bond_options[\"mode\"]
KeyError: 'mode'
'","errorVerbose":"failed to execute nmstatectl show: 'exit status 1' '' 'Exception ignored in: <bound method _NmClient.__del__ of <libnmstate.nm.nmclient._NmClient object at 0x7f4c5d113630>>
Traceback (most recent call last):
  File \"/usr/lib/python3.6/site-packages/libnmstate/nm/nmclient.py\", line 275, in __del__
    \"_NmClient.delete_client() should be explicitly called \"
libnmstate.error.NmstateInternalError: _NmClient.delete_client() should be explicitly called before python GC clean up the object.
Traceback (most recent call last):
  File \"/usr/bin/nmstatectl\", line 11, in <module>
    load_entry_point('nmstate==0.2.10', 'console_scripts', 'nmstatectl')()
  File \"/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py\", line 59, in main
    return args.func(args)
  File \"/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py\", line 203, in show
    state = _filter_state(libnmstate.show(), args.only)
  File \"/usr/lib/python3.6/site-packages/libnmstate/deprecation.py\", line 40, in wrapper
    return func(*args, **kwargs)
  File \"/usr/lib/python3.6/site-packages/libnmstate/nm/nmclient.py\", line 96, in wrapped
    ret = func(*args, **kwargs)
  File \"/usr/lib/python3.6/site-packages/libnmstate/netinfo.py\", line 46, in show
    report = {Constants.INTERFACES: _interfaces()}
  File \"/usr/lib/python3.6/site-packages/libnmstate/netinfo.py\", line 115, in _interfaces
    iface_info.update(_ifaceinfo_bond(bondinfo))
  File \"/usr/lib/python3.6/site-packages/libnmstate/netinfo.py\", line 132, in _ifaceinfo_bond
    bondinfo = nm.translator.Nm2Api.get_bond_info(devinfo)
  File \"/usr/lib/python3.6/site-packages/libnmstate/nm/translator.py\", line 101, in get_bond_info
    bond_mode = bond_options[\"mode\"]
KeyError: 'mode'
'
error running nmstatectl show

```

**Comment by ffmancera** [comment] 2021-05-26 12:28
Hi! I've not been able to reproduce this anymore and it should be fixed in 0.3 and 1.0 because the code changed a lot. Please, re-open if it is still happening. Thank you!

**Closed as completed by ffmancera** 2021-05-26 12:28 UTC
