### ISSUE TITLE
RFE - Add support for specifying zone (firewalld)

### ISSUE THREAD

**Issue by p3ck** [nmstate/nmstate#1837] opened 2022-03-24 20:48 UTC
## Describe the bug
Currently there is no way to specify which zone an interface should be in when saving or creating via nmstate

## Nmstate version
- 1.2.1

## NetworkManager version
- 1.37.2-1.el8

## Platform
- CentOS Stream 8

## How reproducible
- 100%

## Steps to Reproduce
Use either
nmcli connection modify <INTERFACE> connection.zone <ZONE>
or
firewall-cmd --zone <ZONE> --change-interface <INTERFACE>

**Comment by dsneddon** [comment] 2023-10-10 08:17
I would like to add a +1 vote for this feature. I am implementing firewall zone support for os-net-config and zones are not supported in nmstate yet. We will need this feature in nmstate in the long term since os-net-config support for network init-scripts (ifcfg files) is deprecated and will not be supported in the future. We will only be using the nmstate backend and then phasing os-net-config out completely and only use nmstate directly (see the nmstate-operator in OpenShift).

**Comment by cathay4t** [comment] 2023-10-19 06:04
The zone information is invented by firewalld and nmstate intend to be neutral on backends.

Please use firewalld dbus interface directly.

**Comment by cathay4t** [comment] 2023-10-19 07:17
Closing as won't fix. Please feel free to reopen if think more discussion required.

**Closed as completed by cathay4t** 2023-10-19 07:17 UTC

**Comment by dsneddon** [comment] 2023-10-24 02:59
I'm not sure it's proper to close this bug. I'm not asking for support for managing creating/deleting firewall zones, but rather to assign which zone an interface belongs to. The problem is that without this issue nmstate will delete the zone information from the ifcfg file every time it updates the interface, and the info needs to be stored in NetworkManager. 

Firewalld does support dbus, but this is from the documentation on firewalld dbus support (see https://firewalld.org/documentation/man-pages/firewalld.zone.html) :

"interface    Is an optional empty-element tag and can be used several times. It can be 
used to bind an interface to a zone. You don't need this for 
NetworkManager-managed interfaces, because NetworkManager binds interfaces 
to zones automatically. See also 'How to set or change a zone for a connection?' in 
[firewalld.zones(5)](https://firewalld.org/documentation/man-
pages/firewalld.zones.html). You can use it as a fallback mechanism for interfaces 
that can't be managed via NetworkManager. An interface"

So the way I read that is that we must use NetworkManager to store which zone an interface belongs to. Am I misreading that?

**Comment by aleskandro** [comment] 2023-12-09 15:31
Hi, I understand the scope of the project wants to be agnostic from the firewalld specific implementation, but having to run a bunch of `nmcli` staments or finding alternative ways to change the firewalld zone in the NetworkManager connections generated through the whole configuration pushed via nmstate is kind of uncomfortable. 

Is there any chance we can re-open this issue? I don't believe a solution can't be found to compromise between this request and the scope of the project.

**Comment by imsedgar** [comment] 2023-12-11 02:50
If I use `nmcli show eno1|grep zone` for example, then I get a line with `connection.zone:`. The value is either empty (`--`) or a zone name, e.g. `work`.
For NetworkManager, and for nmstate, it is just a value that can be set to a string. Yes, it is used by firewalld, but nmstate has nothing to do with firewalld if it implements this feature. `zone` is just another (important!) parameter which can be located on `interface` and mapped to `connection.zone` (value to parameter `zone` in section `connection`) of NetworkManager connection file (e.g. `/etc/NetworkManager/system-connections/eno1.nmconnection` in this example).

Please, reopen this issue and implement this feature!
I think it is important to many users because the main network interface of servers and workstations with static configuration is often set to a non-default firewalld zone to allow more services than the default.

Many thanks in advance!

**Comment by imsedgar** [comment] 2023-12-11 03:15
Using the same method as described above it would be good if other `connection` options will be supported.
Especially I need to use `connection.autoconnect` (boolean value) and `connection.autoconnect-priority` (number) to configure an additional fallback ethernet connection if configured bond (lacp) did not come up for some reason.
