### ISSUE TITLE
nmstatectl: Properly sort the priorities

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#940] opened 2020-03-13 09:34 UTC
Currently, nmstatectl show OVS bond as:

```yml
    port:
    - name: veth0_ep
    - link-aggregation:
        mode: balance-slb
        slaves:
        - name: veth1_ep
        - name: veth2_ep
      name: ovs-lagg0
```

Expected:

```yml

    port:
    - name: veth0_ep
    - name: ovs-lagg0
      link-aggregation:
        mode: balance-slb
        slaves:
        - name: veth1_ep
        - name: veth2_ep
```

**Comment by cathay4t** [comment] 2020-03-13 09:34
downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1806474

**Comment by cathay4t** [comment] 2020-03-13 09:37
@ffmancera Do you willing to take this for next major release of nmstate?

**Comment by tyll** [comment] 2020-03-13 09:49
Seems to be a duplicate of #840 - also IMHO it is a feature not a bug and a cosmetic problem unless I am missing something.

**Comment by Sudhan97** [comment] 2020-03-13 10:30
Can I work on this issue, I'm currently learning the codebase. #840 is already been assigned.

**Comment by ffmancera** [comment] 2020-03-13 12:00
> Can I work on this issue, I'm currently learning the codebase. But #840 issue is already been assigned.

I am sorry, please consider taking another issue. This issue is duplicated and already assigned. Thank you!

**Closed** 2020-03-13 12:35 UTC
Labels: Low priority, good first issue, next release
