### ISSUE TITLE
Nmstate crashes with multi-connect=3

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#1480] opened 2021-01-15 14:51 UTC
## Describe the bug
Got the following error when editing ethernet interfaces with connection.multi-connect enabled:
```
      2021-01-15 14:01:12,153 root         DEBUG    Async action: Rollback to checkpoint /org/freedesktop/NetworkManager/Checkpoint/2 finished                                                                                                
      2021-01-15 14:01:12,201 root         DEBUG    Active connection of device None has been replaced
      2021-01-15 14:01:12,202 root         DEBUG    Connection activation succeeded: dev=enp2s0, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_IP_CONFIG of type NM.
DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_LIFETIME_BOUND_TO_PROFILE_VISIBILITY of type NM.ActivationStateFlags>                                                                      
      2021-01-15 14:01:12,202 root         DEBUG    Async action: Waiting for rolling back enp2s0 finished
      Traceback (most recent call last):
        File "/usr/bin/nmstatectl", line 11, in <module>
          load_entry_point('nmstate==0.3.4', 'console_scripts', 'nmstatectl')()
        File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 67, in main
          return args.func(args)
        File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 267, in apply
          args.save_to_disk,
        File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 289, in apply_state
          save_to_disk=save_to_disk,
        File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 71, in apply
          _apply_ifaces_state(plugins, net_state, verify_change, save_to_disk)
        File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 104, in _apply_ifaces_state
          plugin.apply_changes(net_state, save_to_disk)
        File "/usr/lib/python3.6/site-packages/libnmstate/nm/plugin.py", line 174, in apply_changes
          nm_applier.apply_changes(self.context, net_state, save_to_disk)
        File "/usr/lib/python3.6/site-packages/libnmstate/nm/applier.py", line 154, in apply_changes
          _set_ifaces_admin_state(context, ifaces_desired_state, con_profiles)
        File "/usr/lib/python3.6/site-packages/libnmstate/nm/applier.py", line 179, in _set_ifaces_admin_state
          new_ifaces = _get_new_ifaces(context, con_profiles)
        File "/usr/lib/python3.6/site-packages/libnmstate/nm/applier.py", line 372, in _get_new_ifaces
          nmdev = context.get_nm_dev(ifname)
        File "/usr/lib/python3.6/site-packages/libnmstate/nm/context.py", line 220, in get_nm_dev
          return self.client.get_device_by_iface(iface_name)
      TypeError: Argument 1 does not allow None as a value
      '
```
## Nmstate version
- Version nmstate-0.3.4

## NetworkManager version
- Version NetworkManager-1.26

## Platform
- Platform: el8

## How reproducible
- 100%

## Steps to Reproduce
1. Run: ' nmcli connection add type ethernet ifname "*" connection.multi-connect multiple connection.id "Wired connection"` 
2. Apply the following state: 
```yaml
    interfaces:
    - name: eth1
      state: up
      type: ethernet
    - name: eth2
      state: up
      type: ethernet
```

## Nmstate output
- Expected output:
Should not crash and apply the state

- Current output:
Crash.

**Comment by cathay4t** [comment] 2021-01-15 15:10
Close as duplicate of #1474

**Closed as completed by cathay4t** 2021-01-15 15:10 UTC
