### ISSUE TITLE
Support NetworkManager unmanaged interface

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#941] opened 2020-03-13 09:43 UTC
When certain interface in unmanaged by NM, the information showed by nmstate is incorrect.

To achieve that, a new backend/plugin could introduced with higher priority of NM(allow its information override NM provided).

**Comment by tyll** [comment] 2020-07-01 10:00
Is this a duplicate of #1136

**Comment by ffmancera** [comment] 2022-08-31 14:05
This was done by using Nispor!

**Closed by ffmancera** 2022-08-31 14:05 UTC
Labels: New Feature
