### ISSUE TITLE
Bridge should take over NICs MAC address

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#733] opened 2020-02-03 17:45 UTC
As a user of nmstate, I expect that when I use DHCP to obtain IP for my bridge, it should be the same IP as was originally on the bridge's port. While this used to be the case, starting with Fedora 31 MACAddressPolicy=persistent has been enabled by for virtual devices https://github.com/systemd/systemd/blob/master/NEWS#L499. Due to this change we are not getting the expected IP anymore.

I don't know whether we should go against platform in nmstate, but this change is a serious issue for kubernetes-nmstate and oVirt's use-cases. What do we do about it? Can we change nmstate, so it behaves as we are used to or do we leave it to users (kubernetes-nmstate and oVirt) to either set the MAC explicitly or configure system not to persist the MAC by default?

**Comment by ffmancera** [comment] 2020-02-10 13:47
@almusil @phoracek Do you think this issue is already solved?

**Comment by phoracek** [comment] 2020-02-10 13:52
I have not tested it yet on kubernetes-nmstate since we are still on 1.20.

**Comment by tyll** [comment] 2020-02-13 11:25
@phoracek is it important for you to get this fixed in Fedora right now? It is not a problem in CentOS 8.

**Comment by phoracek** [comment] 2020-02-13 11:48
Not for Fedora, but we need it on 1.20. But I suppose you cannot fix that, can you?

**Comment by cathay4t** [comment] 2020-02-13 13:25
I guess systemd already received enough complains, they included a long changelog explaining this:

https://github.com/systemd/systemd/blob/master/NEWS#L1004

As it said, if user is impacted by this, they can use 

```
          # /etc/systemd/network/98-bridge-inherit-mac.link
          [Match]
          Type=bridge

          [Link]
          MACAddressPolicy=none
```

For Fedora, they can change whatever they like.
For RHEL, they will not change that dramatically, if they do, their QE will create a regression bug.

Regarding what nmstate can do, the best we can do is document this and instruct user to
change systemd config if they want bridge to take the kernel MAC address.

**Comment by tyll** [comment] 2020-02-13 14:06
> Not for Fedora, but we need it on 1.20. But I suppose you cannot fix that, can you?

The issue that you describe here does not depend on the NM version. Do you maybe mean the problem that was fixed in #708? I do not see how we can fix this with 1.20 because it required a change in NM.

**Comment by phoracek** [comment] 2020-02-13 14:08
Gotcha! Thanks @tyll and @cathay4t.

I will add the workaround Gris mentioned into out docs and consider it done. We are moving to 1.22 in a few days.

**Comment by cathay4t** [comment] 2020-02-13 14:25
@phoracek Another background history on #708,  NM 1.20 or older version has a [bug] when using NetworkManager internal DHCP client. So we expect user to use dhclient for this use case.

With #708 (in nmstate-0.2.2) and NM 1.22, you can use NetworkManager internal DHCP client now(RHEL 8 default setting) or the dhclient to get the expected results.

For Bridge not takes over its first slave's MAC address, that's a systemd's issue:

Fedora 30- and RHEL 8 does on have this problem yet(we have test case monitor this).

Fedora 31+ need workaround on `/etc/systemd/network/98-bridge-inherit-mac.link` above.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1749358

**Comment by cathay4t** [comment] 2020-02-17 02:24
@ffmancera Can we close this issue now?

**Comment by ffmancera** [comment] 2020-02-20 13:38
> @phoracek Another background history on #708, NM 1.20 or older version has a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1749358) when using NetworkManager internal DHCP client. So we expect user to use dhclient for this use case.
> 
> With #708 (in nmstate-0.2.2) and NM 1.22, you can use NetworkManager internal DHCP client now(RHEL 8 default setting) or the dhclient to get the expected results.
> 
> For Bridge not takes over its first slave's MAC address, that's a systemd's issue:
> 
> Fedora 30- and RHEL 8 does on have this problem yet(we have test case monitor this).
> 
> Fedora 31+ need workaround on `/etc/systemd/network/98-bridge-inherit-mac.link` above.

Should we document this somewhere?

**Comment by cathay4t** [comment] 2020-02-27 04:35
> Should we document this somewhere?

This github issue is the good document.

**Comment by cathay4t** [comment] 2020-08-27 15:42
I have include the detail in our API document:

https://www.nmstate.io/devel/api.html#limitations-of-linux-bridge-interface

**Closed by cathay4t** 2020-08-27 15:42 UTC
Labels: Low priority
